# Generated by Django 4.2.4 on 2023-11-24 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketMeetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=255)),
                ('meeting_date', models.CharField(max_length=255)),
                ('meeting_time', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ticketmeetings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('requestor_id', models.CharField(max_length=255)),
                ('assignee_id', models.CharField(max_length=255)),
                ('opened_on', models.CharField(max_length=255)),
                ('updated_on', models.CharField(max_length=255)),
                ('priority', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255, unique=True)),
                ('user_permissions', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSchedules',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.users')),
                ('schedule', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'userschedules',
                'managed': False,
            },
        ),
    ]
